# ==========================================
# Configuração da Aplicação
# ==========================================
spring.application.name=tasks-api
server.port=8080

# ==========================================
# Banco de Dados H2 (em memória)
# ==========================================
spring.datasource.url=jdbc:h2:mem:tasksdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# Console H2 (http://localhost:8080/h2-console)
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# JPA / Hibernate e Inicialização
# ==========================================
# 1. 'update' cria as tabelas se elas não existirem
spring.jpa.hibernate.ddl-auto=update

# 2. ESSA LINHA É A CHAVE: Força o Spring a esperar as tabelas serem criadas para só DEPOIS rodar o data.sql
spring.jpa.defer-datasource-initialization=true

# 3. Garante que o script de dados sempre rode
spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Logs
# ==========================================
logging.level.com.tasks=DEBUG